const PRODUCTS = [
  {
    id: "1",
    slug: "bcaa-recovery-formula",
    name: "BCAA Recovery Formula",
    price: 29.99,
    images: ["/images/bcaa1.png"],
    shortDescription: "Premium BCAA supplement to power recovery",
    description: "Full description here...",
    category: "Supplements",
    rating: 4.6,
    stock: 50,
  },
  {
    id: "2",
    slug: "whey-protein-isolate",
    name: "Premium Whey Protein Isolate",
    price: 49.99,
    images: ["/images/wheyiso.jpg"],
  },
  {
    id: "3",
    slug: "creatine-monohydrate",
    name: "Creatine Monohydrate",
    price: 19.99,
    images: ["/images/creatine.png"],
    shortDescription: "Boost strength and performance with pure creatine.",
    description: "Full description here...",
    category: "Supplements",
    rating: 4.8,
    stock: 100,
  },
  {
    id: "4",
    slug: "pre-workout-ignite",
    name: "Pre-Workout Ignite",
    price: 34.99,
    images: ["/images/preworkout.png"],
    shortDescription: "Explosive energy and focus for your workouts.",
    description: "Full description here...",
    category: "Supplements",
    rating: 4.5,
    stock: 75,
  },
  {
    id: "5",
    slug: "protein-bar-variety-pack",
    name: "Protein Bar Variety Pack",
    price: 24.99,
    images: ["/images/proteinbar.png"],
    shortDescription: "Delicious and convenient protein on the go.",
    description: "Full description here...",
    category: "Nutrition",
    rating: 4.7,
    stock: 120,
  },
  {
    id: "6",
    slug: "gym-duffel-bag",
    name: "Premium Gym Duffel Bag",
    price: 39.99,
    images: ["/images/gymbag.png"],
    shortDescription: "Durable and spacious bag for all your gym essentials.",
    description: "Full description here...",
    category: "Accessories",
    rating: 4.3,
    stock: 60,
  },
  {
    id: "7",
    slug: "resistance-band-set",
    name: "Resistance Band Set",
    price: 15.99,
    images: ["/images/resistancebands.png"],
    shortDescription:
      "Versatile bands for strength training and rehabilitation.",
    description: "Full description here...",
    category: "Accessories",
    rating: 4.4,
    stock: 80,
  },
];

export default PRODUCTS;
